import { LitElement, PropertyValues, TemplateResult } from 'lit';
import { OscdIcon } from '@omicronenergy/oscd-ui/icon/OscdIcon.js';
import { OscdListItem } from '@omicronenergy/oscd-ui/list/OscdListItem.js';
import { OscdIconButton } from '@omicronenergy/oscd-ui/iconbutton/OscdIconButton.js';
import { OscdDivider } from '@omicronenergy/oscd-ui/divider/OscdDivider.js';
import { OscdMenu } from '@omicronenergy/oscd-ui/menu/OscdMenu.js';
import { OscdMenuItem } from '@omicronenergy/oscd-ui/menu/OscdMenuItem.js';
import { VirtualizedFilteredList } from '../foundation/virtualized-filtered-list.js';
import { ServiceType } from '../foundation.js';
declare const ControlBlockList_base: typeof LitElement & import("@open-wc/scoped-elements/lit-element.js").ScopedElementsHostConstructor;
export declare class ControlBlockList extends ControlBlockList_base {
    static scopedElements: {
        'oscd-icon': typeof OscdIcon;
        'oscd-list-item': typeof OscdListItem;
        'oscd-icon-button': typeof OscdIconButton;
        'oscd-divider': typeof OscdDivider;
        'oscd-menu': typeof OscdMenu;
        'oscd-menu-item': typeof OscdMenuItem;
        'virtualized-filtered-list': typeof VirtualizedFilteredList;
    };
    doc: XMLDocument;
    docVersion?: unknown;
    serviceType: ServiceType;
    private menuControlElement;
    private controlBlockMenu;
    private selectedControl;
    private selectedDataSet;
    private get controlSelector();
    private get controlIcon();
    private onOpenDocReset;
    connectedCallback(): void;
    disconnectedCallback(): void;
    protected willUpdate(changedProperties: PropertyValues): void;
    private onSelect;
    private openControlMenu;
    private onMenuEdit;
    private onMenuEditDataSet;
    private onMenuEditSmvOpts;
    private onMenuEditCommunication;
    private onMenuRemove;
    private renderControl;
    private renderControlBlockMenu;
    protected updated(): void;
    protected firstUpdated(): void;
    private buildRows;
    private renderRow;
    private matchRow;
    private rowKey;
    render(): TemplateResult;
    static styles: import("lit").CSSResult;
}
export {};
